"""audit log schemas for LLM interaction tracking"""
from __future__ import annotations
from typing import List, Dict, Any, Optional, Literal
from pydantic import BaseModel, Field
import json


class LLMInteraction(BaseModel):
    """Single LLM prompt-response interaction."""
    interaction_id: str
    timestamp: str
    phase: Literal["phase_1_presentation", "phase_2_pa", "phase_2_utilization_review", "phase_2_pa_appeal", "phase_3_claims", "phase_4_financial"]
    agent: Literal["provider", "payor", "environment"]
    action: str  # e.g., "order_tests", "concurrent_review", "submit_appeal", "review_appeal"
    system_prompt: str
    user_prompt: str
    llm_response: str
    parsed_output: Dict[str, Any] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class EnvironmentAction(BaseModel):
    """environment agent action (test result generation, noise injection, etc)"""
    action_id: str
    timestamp: str
    phase: str
    action_type: str  # "generate_test_result", "inject_noise", "calculate_settlement"
    description: str
    outcome: Dict[str, Any] = Field(default_factory=dict)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AgentConfiguration(BaseModel):
    """agent behavioral parameters and system prompt"""
    agent_name: str
    behavioral_parameters: Dict[str, Any]
    system_prompt: str


class AuditLog(BaseModel):
    """Complete audit log for a case simulation."""
    case_id: str
    simulation_start: str
    simulation_end: Optional[str] = None
    interactions: List[LLMInteraction] = Field(default_factory=list)
    environment_actions: List[EnvironmentAction] = Field(default_factory=list)
    agent_configurations: List[AgentConfiguration] = Field(default_factory=list)
    summary: Dict[str, Any] = Field(default_factory=dict)

    def save_to_json(self, filepath: str):
        """save audit log to JSON file"""
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(self.model_dump(), f, indent=2)

    def save_to_markdown(self, filepath: str):
        """save audit log to markdown file with full interaction details"""
        lines = []

        # header
        lines.append(f"# Audit Log: {self.case_id}")
        lines.append("")
        lines.append(f"**Simulation Start:** {self.simulation_start}")
        lines.append(f"**Simulation End:** {self.simulation_end or 'In Progress'}")
        lines.append("")

        # guide section
        lines.append("## How to Read This Audit Log")
        lines.append("")
        lines.append("Each interaction below contains the following sections:")
        lines.append("")
        lines.append("| Section | Description | Source |")
        lines.append("|---------|-------------|--------|")
        lines.append("| **System Prompt** | Agent's role, incentives, and behavioral parameters | Defined in `prompts.py`, constant per agent |")
        lines.append("| **User Prompt** | Task-specific instructions with case data | Generated per interaction from case/prior outputs |")
        lines.append("| **LLM Response** | Raw text returned by LLM | Generated by LLM (may include extra commentary) |")
        lines.append("| **Parsed Output** | Structured JSON extracted from LLM response | Parsed from LLM response, **actually used by simulation** |")
        lines.append("| **Rationale/Context** *(if present)* | LLM's reasoning explanation | Spontaneously added by LLM (not requested, not used) |")
        lines.append("")
        lines.append("**Note:** Only the \"Parsed Output\" is used to drive simulation decisions. Extra sections like \"Rationale\" are logged for transparency but do not affect outcomes.")
        lines.append("")

        # summary
        if self.summary:
            lines.append("## Summary")
            lines.append("")
            lines.append(f"- **Total Interactions:** {self.summary.get('total_interactions', 0)}")
            lines.append("")

            if "interactions_by_phase" in self.summary:
                lines.append("**Interactions by Phase:**")
                for phase, count in self.summary["interactions_by_phase"].items():
                    lines.append(f"- {phase}: {count}")
                lines.append("")

            if "interactions_by_agent" in self.summary:
                lines.append("**Interactions by Agent:**")
                for agent, count in self.summary["interactions_by_agent"].items():
                    lines.append(f"- {agent}: {count}")
                lines.append("")

            if "behavioral_parameters" in self.summary:
                lines.append("**Behavioral Parameters:**")
                params = self.summary["behavioral_parameters"]
                if "provider" in params:
                    lines.append("- **Provider:**")
                    for key, value in params["provider"].items():
                        lines.append(f"  - {key}: {value}")
                if "payor" in params:
                    lines.append("- **Payor:**")
                    for key, value in params["payor"].items():
                        lines.append(f"  - {key}: {value}")
                lines.append("")

            if "truth_check_summary" in self.summary:
                lines.append("**Truth Check Summary:**")
                tc = self.summary["truth_check_summary"]
                if tc.get("phase2"):
                    lines.append("- **Phase 2 (PA Request):**")
                    lines.append(f"  - Deceptive: {tc['phase2'].get('is_deceptive', 'N/A')}")
                    lines.append(f"  - Deception Score: {tc['phase2'].get('deception_score', 0.0):.2f}")
                    lines.append(f"  - Hallucinated Claims: {len(tc['phase2'].get('hallucinated_claims', []))}")
                if tc.get("phase3"):
                    lines.append("- **Phase 3 (Appeal):**")
                    lines.append(f"  - Deceptive: {tc['phase3'].get('is_deceptive', 'N/A')}")
                    lines.append(f"  - Deception Score: {tc['phase3'].get('deception_score', 0.0):.2f}")
                    lines.append(f"  - Hallucinated Claims: {len(tc['phase3'].get('hallucinated_claims', []))}")
                    if tc['phase2'] and tc['phase3']:
                        doubled_down = tc['phase3']['deception_score'] > tc['phase2']['deception_score']
                        lines.append(f"  - **Doubled Down on Lies:** {'Yes' if doubled_down else 'No'}")
                lines.append("")

        lines.append("---")
        lines.append("")

        # detailed interactions
        for i, interaction in enumerate(self.interactions, 1):
            # interaction header
            phase_name = self._format_phase_name(interaction.phase)
            lines.append(f"## Interaction {i}: {phase_name}")
            lines.append("")
            lines.append(f"**Timestamp:** {interaction.timestamp}")
            lines.append(f"**Agent:** {interaction.agent.capitalize()}")
            lines.append(f"**Action:** {interaction.action.replace('_', ' ').title()}")
            lines.append("")

            # metadata
            if interaction.metadata:
                lines.append("**Metadata:**")
                for key, value in interaction.metadata.items():
                    if isinstance(value, (list, dict)):
                        lines.append(f"- {key}: `{json.dumps(value)}`")
                    else:
                        lines.append(f"- {key}: {value}")
                lines.append("")

            # system prompt
            lines.append("### System Prompt")
            lines.append("")
            lines.append("```")
            lines.append(interaction.system_prompt)
            lines.append("```")
            lines.append("")

            # user prompt
            lines.append("### User Prompt")
            lines.append("")
            lines.append("```")
            lines.append(interaction.user_prompt)
            lines.append("```")
            lines.append("")

            # llm response
            lines.append("### LLM Response")
            lines.append("")
            lines.append("```")
            lines.append(interaction.llm_response)
            lines.append("```")
            lines.append("")

            # parsed output
            lines.append("### Parsed Output")
            lines.append("")
            lines.append("```json")
            lines.append(json.dumps(interaction.parsed_output, indent=2))
            lines.append("```")
            lines.append("")
            lines.append("---")
            lines.append("")

        # write to file
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))

    def _format_phase_name(self, phase: str) -> str:
        """format phase identifier as readable name"""
        phase_names = {
            "phase_2_pa": "Phase 2: Prior Authorization",
            "phase_2_pa_appeal": "Phase 2: PA Appeal Process",
            "phase_3_claims": "Phase 3: Claims Adjudication",
            "phase_4_financial": "Phase 4: Financial Settlement"
        }
        return phase_names.get(phase, phase.replace("_", " ").title())

    def save_to_folder(self, output_dir: str):
        """save audit log split into organized folder structure

        creates:
            {output_dir}/
                00_config.md         - agent configs
                phase2_iter01.md     - P2 iteration 1 (provider + payor)
                phase2_iter02.md     - P2 iteration 2 ...
                phase3_claims.md     - claim submission + adjudication
                summary.md           - compact decision trace
        """
        import os
        os.makedirs(output_dir, exist_ok=True)

        # 1. Config file - agent settings
        config_lines = []
        config_lines.append(f"# Configuration: {self.case_id}")
        config_lines.append("")
        config_lines.append(f"**Simulation:** {self.simulation_start} → {self.simulation_end or 'In Progress'}")
        config_lines.append("")

        if self.summary.get("behavioral_parameters"):
            params = self.summary["behavioral_parameters"]
            config_lines.append("## Agent Parameters")
            config_lines.append("")
            if "provider" in params:
                config_lines.append("### Provider")
                for k, v in params["provider"].items():
                    config_lines.append(f"- {k}: {v}")
                config_lines.append("")
            if "payor" in params:
                config_lines.append("### Payor")
                for k, v in params["payor"].items():
                    config_lines.append(f"- {k}: {v}")
                config_lines.append("")

        with open(os.path.join(output_dir, "00_config.md"), 'w', encoding='utf-8') as f:
            f.write("\n".join(config_lines))

        # 2. Phase 2 files - one per iteration (provider + payor pair)
        phase_2_interactions = [i for i in self.interactions if i.phase == "phase_2_pa"]

        # group by iteration
        iterations = {}
        for interaction in phase_2_interactions:
            iter_num = interaction.metadata.get("iteration", 0)
            if iter_num not in iterations:
                iterations[iter_num] = []
            iterations[iter_num].append(interaction)

        for iter_num, iter_interactions in sorted(iterations.items()):
            iter_lines = []
            iter_lines.append(f"# Phase 2 - Iteration {iter_num}")
            iter_lines.append("")

            for interaction in iter_interactions:
                iter_lines.append(f"## {interaction.agent.capitalize()} - {interaction.action.replace('_', ' ').title()}")
                iter_lines.append("")

                # metadata
                if interaction.metadata:
                    meta_items = [f"{k}={v}" for k, v in interaction.metadata.items()
                                  if k not in ["word_count"]]
                    iter_lines.append(f"**Meta:** {', '.join(meta_items)}")
                    iter_lines.append("")

                # user prompt (collapsible)
                iter_lines.append("<details>")
                iter_lines.append("<summary>User Prompt</summary>")
                iter_lines.append("")
                iter_lines.append("```")
                iter_lines.append(interaction.user_prompt)
                iter_lines.append("```")
                iter_lines.append("</details>")
                iter_lines.append("")

                # parsed output
                iter_lines.append("### Decision")
                iter_lines.append("")
                iter_lines.append("```json")
                iter_lines.append(json.dumps(interaction.parsed_output, indent=2))
                iter_lines.append("```")
                iter_lines.append("")
                iter_lines.append("---")
                iter_lines.append("")

            filename = f"phase2_iter{iter_num:02d}.md"
            with open(os.path.join(output_dir, filename), 'w', encoding='utf-8') as f:
                f.write("\n".join(iter_lines))

        # 3. Phase 3 files - claims adjudication (may have multiple iterations for appeals/resubmissions)
        phase_3_interactions = [i for i in self.interactions if i.phase == "phase_3_claims"]
        if phase_3_interactions:
            # group by iteration (claims can be pended/appealed)
            p3_iterations = {}
            for interaction in phase_3_interactions:
                iter_num = interaction.metadata.get("iteration", interaction.metadata.get("appeal_round", 1))
                if iter_num not in p3_iterations:
                    p3_iterations[iter_num] = []
                p3_iterations[iter_num].append(interaction)

            for iter_num, iter_interactions in sorted(p3_iterations.items()):
                p3_lines = []
                p3_lines.append(f"# Phase 3 - Claims (Round {iter_num})")
                p3_lines.append("")

                for interaction in iter_interactions:
                    p3_lines.append(f"## {interaction.agent.capitalize()} - {interaction.action.replace('_', ' ').title()}")
                    p3_lines.append("")

                    if interaction.metadata:
                        meta_items = [f"{k}={v}" for k, v in interaction.metadata.items()
                                      if k not in ["word_count"]]
                        p3_lines.append(f"**Meta:** {', '.join(meta_items)}")
                        p3_lines.append("")

                    p3_lines.append("<details>")
                    p3_lines.append("<summary>User Prompt</summary>")
                    p3_lines.append("")
                    p3_lines.append("```")
                    p3_lines.append(interaction.user_prompt)
                    p3_lines.append("```")
                    p3_lines.append("</details>")
                    p3_lines.append("")

                    p3_lines.append("### Decision")
                    p3_lines.append("")
                    p3_lines.append("```json")
                    p3_lines.append(json.dumps(interaction.parsed_output, indent=2))
                    p3_lines.append("```")
                    p3_lines.append("")
                    p3_lines.append("---")
                    p3_lines.append("")

                # single iteration -> phase3_claims.md, multiple -> phase3_round01.md etc
                if len(p3_iterations) == 1:
                    filename = "phase3_claims.md"
                else:
                    filename = f"phase3_round{iter_num:02d}.md"
                with open(os.path.join(output_dir, filename), 'w', encoding='utf-8') as f:
                    f.write("\n".join(p3_lines))

        # 4. Summary file
        self.save_summary(os.path.join(output_dir, "summary.md"))

    def save_summary(self, filepath: str):
        """save compact decision trace summary - much smaller than full audit log

        focuses on:
        - simulation config and patient info
        - key decisions by each agent with brief reasoning
        - outcomes and financial results
        """
        lines = []

        # header
        lines.append(f"# Decision Trace: {self.case_id}")
        lines.append("")
        lines.append(f"**Run:** {self.simulation_start} → {self.simulation_end or 'In Progress'}")
        lines.append("")

        # agent configs (compact)
        if self.summary.get("behavioral_parameters"):
            params = self.summary["behavioral_parameters"]
            lines.append("## Agent Configuration")
            lines.append("")
            if "provider" in params:
                prov = params["provider"]
                prov_items = ", ".join(f"{k}={v}" for k, v in prov.items())
                lines.append(f"**Provider:** {prov_items}")
            if "payor" in params:
                pay = params["payor"]
                pay_items = ", ".join(f"{k}={v}" for k, v in pay.items())
                lines.append(f"**Payor:** {pay_items}")
            lines.append("")

        # decision trace by phase
        lines.append("## Decision Trace")
        lines.append("")

        # group interactions by phase
        phase_2_interactions = [i for i in self.interactions if i.phase == "phase_2_pa"]
        phase_3_interactions = [i for i in self.interactions if i.phase == "phase_3_claims"]

        # phase 2 summary
        if phase_2_interactions:
            lines.append("### Phase 2: Prior Authorization")
            lines.append("")
            lines.append("| Iter | Agent | Action | Key Decision | Outcome |")
            lines.append("|------|-------|--------|--------------|---------|")

            for interaction in phase_2_interactions:
                iter_num = interaction.metadata.get("iteration", "?")
                agent = interaction.agent.upper()[:4]
                action = interaction.action.replace("_request", "").replace("_review", "")

                # extract key decision info from parsed output
                parsed = interaction.parsed_output or {}
                if interaction.agent == "provider":
                    req_type = parsed.get("request_type", interaction.metadata.get("request_type", "?"))
                    conf = parsed.get("confidence", "?")
                    key_decision = f"conf={conf:.1f}" if isinstance(conf, float) else f"conf={conf}"
                    outcome = req_type
                else:
                    status = parsed.get("authorization_status", "?")
                    reason = parsed.get("denial_reason", "")[:30] if parsed.get("denial_reason") else ""
                    key_decision = status.upper()
                    outcome = reason + "..." if reason else status

                lines.append(f"| {iter_num} | {agent} | {action} | {key_decision} | {outcome} |")

            lines.append("")

        # phase 3 summary
        if phase_3_interactions:
            lines.append("### Phase 3: Claims Adjudication")
            lines.append("")
            lines.append("| Agent | Action | Key Decision | Amount |")
            lines.append("|-------|--------|--------------|--------|")

            for interaction in phase_3_interactions:
                agent = interaction.agent.upper()[:4]
                action = interaction.action.replace("claim_", "")
                parsed = interaction.parsed_output or {}

                if interaction.agent == "provider":
                    # extract diagnosis and amount
                    claim = parsed.get("claim_submission", parsed)
                    codes = claim.get("diagnosis_codes", [])
                    dx = codes[0].get("icd10", "?") if codes else "?"
                    amount = claim.get("total_amount_billed", "?")
                    key_decision = f"Dx: {dx}"
                    amt_str = f"${amount:,.0f}" if isinstance(amount, (int, float)) else str(amount)
                else:
                    status = parsed.get("authorization_status") or parsed.get("claim_status") or "?"
                    key_decision = status.upper()
                    amt = parsed.get("total_paid_amount")
                    if amt is None:
                        amt = parsed.get("approved_amount")
                    if amt is None:
                        line_adjs = parsed.get("line_adjudications", [])
                        if line_adjs:
                            paid_vals = [
                                adj.get("paid_amount")
                                for adj in line_adjs
                                if isinstance(adj.get("paid_amount"), (int, float))
                            ]
                            amt = sum(paid_vals) if paid_vals else None
                    amt_str = f"${amt:,.0f}" if isinstance(amt, (int, float)) else "-"

                lines.append(f"| {agent} | {action} | {key_decision} | {amt_str} |")

            lines.append("")

        # outcome summary
        lines.append("## Outcome")
        lines.append("")
        if self.summary:
            lines.append(f"- **Total Interactions:** {self.summary.get('total_interactions', 0)}")
            if "interactions_by_phase" in self.summary:
                p2_count = self.summary["interactions_by_phase"].get("phase_2_pa", 0)
                p3_count = self.summary["interactions_by_phase"].get("phase_3_claims", 0)
                lines.append(f"- **Phase 2 Iterations:** {p2_count // 2}")  # div by 2 for provider+payor
                lines.append(f"- **Phase 3 Steps:** {p3_count}")

        # write
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))

    def save_to_markdown_compact(self, filepath: str, include_prompts: bool = False):
        """save audit log with reduced verbosity

        args:
            filepath: output file path
            include_prompts: if False (default), omit system prompts and show only user prompt summary
        """
        lines = []

        # header
        lines.append(f"# Audit Log: {self.case_id}")
        lines.append("")
        lines.append(f"**Simulation Start:** {self.simulation_start}")
        lines.append(f"**Simulation End:** {self.simulation_end or 'In Progress'}")
        lines.append("")

        # summary (same as before)
        if self.summary:
            lines.append("## Summary")
            lines.append("")
            lines.append(f"- **Total Interactions:** {self.summary.get('total_interactions', 0)}")

            if "interactions_by_phase" in self.summary:
                lines.append("- **By Phase:** " + ", ".join(f"{k}: {v}" for k, v in self.summary["interactions_by_phase"].items()))

            if "behavioral_parameters" in self.summary:
                params = self.summary["behavioral_parameters"]
                if "provider" in params:
                    prov = params["provider"]
                    prov_items = ", ".join(f"{k}={v}" for k, v in prov.items())
                    lines.append(f"- **Provider:** {prov_items}")
                if "payor" in params:
                    pay = params["payor"]
                    pay_items = ", ".join(f"{k}={v}" for k, v in pay.items())
                    lines.append(f"- **Payor:** {pay_items}")
            lines.append("")

        lines.append("---")
        lines.append("")

        # interactions - compact format
        for i, interaction in enumerate(self.interactions, 1):
            phase_name = self._format_phase_name(interaction.phase)
            lines.append(f"## {i}. {phase_name} - {interaction.agent.capitalize()}")
            lines.append("")
            lines.append(f"**Action:** {interaction.action.replace('_', ' ').title()}")

            # metadata (compact)
            if interaction.metadata:
                meta_items = [f"{k}={v}" for k, v in interaction.metadata.items()
                              if k not in ["word_count", "cache_hit"]]
                if meta_items:
                    lines.append(f"**Meta:** {', '.join(meta_items)}")
            lines.append("")

            # user prompt (optional, truncated)
            if include_prompts:
                lines.append("<details>")
                lines.append("<summary>User Prompt (click to expand)</summary>")
                lines.append("")
                lines.append("```")
                # truncate long prompts
                prompt = interaction.user_prompt
                if len(prompt) > 2000:
                    prompt = prompt[:2000] + "\n... [truncated]"
                lines.append(prompt)
                lines.append("```")
                lines.append("</details>")
                lines.append("")

            # parsed output only (skip raw LLM response - it's redundant)
            lines.append("### Decision")
            lines.append("")
            lines.append("```json")
            lines.append(json.dumps(interaction.parsed_output, indent=2))
            lines.append("```")
            lines.append("")
            lines.append("---")
            lines.append("")

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))
